kind: pipeline
name: basevel

steps:
- name: install
  image: composer
  commands:
  - composer install

- name: test
  image: php:7
  commands:
  - vendor/bin/phpunit --configuration config.xml

services:
  - name: redis
    image: redis:latest

  - name: mysql
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: example_pw
